
using System.ComponentModel.DataAnnotations.Schema;


// This file was automatically generated by the T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `ConnectionString`
//     Provider:               `Npgsql`
//     Schema:                 `public`
//     Include Views:          `true`
//
//     Last Generated:         `11/13/2025 7:44:10 PM`



namespace CFBROrders.SDK.Models
{
    [Table("audit_log")]
    public partial class AuditLog
    {
        [Column("id")]
        public string Id { get; set; }
        [Column("user_id")]
        public string UserId { get; set; }
        [Column("event")]
        public string Event { get; set; }
        [Column("timestamp")]
        public string Timestamp { get; set; }
        [Column("data")]
        public string? Data { get; set; }
        [Column("cip")]
        public string? Cip { get; set; }
        [Column("ua")]
        public string? Ua { get; set; }
    }
    [Table("award_info")]
    public partial class AwardInfo
    {
        [Column("id")]
        public string Id { get; set; }
        [Column("name")]
        public string? Name { get; set; }
        [Column("info")]
        public string? Info { get; set; }
    }
    [Table("awards")]
    public partial class Award
    {
        [Column("id")]
        public string Id { get; set; }
        [Column("user_id")]
        public string? UserId { get; set; }
        [Column("award_id")]
        public string? AwardId { get; set; }
        [Column("award_date")]
        public string? AwardDate { get; set; }
    }
    [Table("bans")]
    public partial class Ban
    {
        [Column("id")]
        public string Id { get; set; }
        [Column("class")]
        public string? Class { get; set; }
        [Column("cip")]
        public string? Cip { get; set; }
        [Column("uname")]
        public string? Uname { get; set; }
        [Column("ua")]
        public string? Ua { get; set; }
        [Column("reason")]
        public string? Reason { get; set; }
    }
    [Table("captchas")]
    public partial class Captcha
    {
        [Column("id")]
        public string Id { get; set; }
        [Column("title")]
        public string? Title { get; set; }
        [Column("content")]
        public string? Content { get; set; }
        [Column("creation")]
        public string? Creation { get; set; }
    }
    [Table("continuation_polls")]
    public partial class ContinuationPoll
    {
        [Column("id")]
        public string Id { get; set; }
        [Column("question")]
        public string? Question { get; set; }
        [Column("incrment")]
        public string? Incrment { get; set; }
        [Column("turn_id")]
        public string? TurnId { get; set; }
    }
    [Table("continuation_responses")]
    public partial class ContinuationResponse
    {
        [Column("id")]
        public string Id { get; set; }
        [Column("poll_id")]
        public string? PollId { get; set; }
        [Column("user_id")]
        public string? UserId { get; set; }
        [Column("response")]
        public string? Response { get; set; }
    }
    [Table("discord_id_logging")]
    public partial class DiscordIdLogging
    {
        [Column("season")]
        public string? Season { get; set; }
        [Column("day")]
        public string? Day { get; set; }
        [Column("territory")]
        public string? Territory { get; set; }
        [Column("user_id")]
        public string? UserId { get; set; }
        [Column("team")]
        public string? Team { get; set; }
        [Column("player")]
        public string? Player { get; set; }
        [Column("mvp")]
        public string? Mvp { get; set; }
        [Column("uname")]
        public string? Uname { get; set; }
        [Column("turns")]
        public string? Turns { get; set; }
        [Column("mvps")]
        public string? Mvps { get; set; }
        [Column("platform")]
        public string? Platform { get; set; }
        [Column("discord_id")]
        public string? DiscordId { get; set; }
        [Column("tname")]
        public string? Tname { get; set; }
        [Column("power")]
        public string? Power { get; set; }
        [Column("weight")]
        public string? Weight { get; set; }
        [Column("stars")]
        public string? Stars { get; set; }
        [Column("current_stars")]
        public string? CurrentStars { get; set; }
    }
    [Table("heat")]
    public partial class Heat
    {
        [Column("name")]
        public string? Name { get; set; }
        [Column("season")]
        public string? Season { get; set; }
        [Column("day")]
        public string? Day { get; set; }
        [Column("cumulative_players")]
        public string? CumulativePlayers { get; set; }
        [Column("cumulative_power")]
        public string? CumulativePower { get; set; }
    }
    [Table("heat_full")]
    public partial class HeatFull
    {
        [Column("name")]
        public string? Name { get; set; }
        [Column("season")]
        public string? Season { get; set; }
        [Column("day")]
        public string? Day { get; set; }
        [Column("cumulative_players")]
        public string? CumulativePlayers { get; set; }
        [Column("cumulative_power")]
        public string? CumulativePower { get; set; }
        [Column("owner")]
        public string? Owner { get; set; }
    }
    [Table("logs")]
    public partial class Log
    {
        [Column("id")]
        public string Id { get; set; }
        [Column("route")]
        public string? Route { get; set; }
        [Column("query")]
        public string? Query { get; set; }
        [Column("payload")]
        public string? Payload { get; set; }
        [Column("timestamp")]
        public string? Timestamp { get; set; }
    }
    [Table("moves")]
    public partial class Move
    {
        [Column("season")]
        public string? Season { get; set; }
        [Column("day")]
        public string? Day { get; set; }
        [Column("territory")]
        public string? Territory { get; set; }
        [Column("user_id")]
        public string? UserId { get; set; }
        [Column("team")]
        public string? Team { get; set; }
        [Column("player")]
        public string? Player { get; set; }
        [Column("mvp")]
        public string? Mvp { get; set; }
        [Column("uname")]
        public string? Uname { get; set; }
        [Column("turns")]
        public string? Turns { get; set; }
        [Column("mvps")]
        public string? Mvps { get; set; }
        [Column("tname")]
        public string? Tname { get; set; }
        [Column("power")]
        public string? Power { get; set; }
        [Column("weight")]
        public string? Weight { get; set; }
        [Column("stars")]
        public string? Stars { get; set; }
        [Column("current_stars")]
        public string? CurrentStars { get; set; }
    }
    [Table("odds")]
    public partial class Odd
    {
        [Column("ones")]
        public string? Ones { get; set; }
        [Column("twos")]
        public string? Twos { get; set; }
        [Column("threes")]
        public string? Threes { get; set; }
        [Column("fours")]
        public string? Fours { get; set; }
        [Column("fives")]
        public string? Fives { get; set; }
        [Column("players")]
        public string? Players { get; set; }
        [Column("teampower")]
        public string? Teampower { get; set; }
        [Column("territorypower")]
        public string? Territorypower { get; set; }
        [Column("chance")]
        public string? Chance { get; set; }
        [Column("team")]
        public string? Team { get; set; }
        [Column("season")]
        public string? Season { get; set; }
        [Column("day")]
        public string? Day { get; set; }
        [Column("territory_name")]
        public string? TerritoryName { get; set; }
        [Column("team_name")]
        public string? TeamName { get; set; }
        [Column("color")]
        public string? Color { get; set; }
        [Column("secondary_color")]
        public string? SecondaryColor { get; set; }
        [Column("tname")]
        public string? Tname { get; set; }
        [Column("prev_owner")]
        public string? PrevOwner { get; set; }
        [Column("mvp")]
        public string? Mvp { get; set; }
    }
    [Table("past_turns")]
    public partial class PastTurn
    {
        [Column("id")]
        public string? Id { get; set; }
        [Column("user_id")]
        public string? UserId { get; set; }
        [Column("territory")]
        public string? Territory { get; set; }
        [Column("mvp")]
        public string? Mvp { get; set; }
        [Column("power")]
        public string? Power { get; set; }
        [Column("multiplier")]
        public string? Multiplier { get; set; }
        [Column("weight")]
        public string? Weight { get; set; }
        [Column("stars")]
        public string? Stars { get; set; }
        [Column("team")]
        public string? Team { get; set; }
        [Column("alt_score")]
        public string? AltScore { get; set; }
        [Column("merc")]
        public string? Merc { get; set; }
        [Column("turn_id")]
        public string? TurnId { get; set; }
    }
    [Table("players")]
    public partial class Player
    {
        [Column("id")]
        public string? Id { get; set; }
        [Column("uname")]
        public string? Uname { get; set; }
        [Column("platform")]
        public string? Platform { get; set; }
        [Column("current_team")]
        public string? CurrentTeam { get; set; }
        [Column("overall")]
        public string? Overall { get; set; }
        [Column("turns")]
        public string? Turns { get; set; }
        [Column("game_turns")]
        public string? GameTurns { get; set; }
        [Column("mvps")]
        public string? Mvps { get; set; }
        [Column("streak")]
        public string? Streak { get; set; }
        [Column("awards")]
        public string? Awards { get; set; }
        [Column("tname")]
        public string? Tname { get; set; }
    }
    [Table("region_ownership")]
    public partial class RegionOwnership
    {
        [Column("owner_count")]
        public string? OwnerCount { get; set; }
        [Column("owners")]
        public int[]? Owners { get; set; }
        [Column("day")]
        public string? Day { get; set; }
        [Column("season")]
        public string? Season { get; set; }
        [Column("region")]
        public string? Region { get; set; }
    }
    [Table("regions")]
    public partial class Region
    {
        [Column("id")]
        public string Id { get; set; }
        [Column("name")]
        public string? Name { get; set; }
        [Column("submap")]
        public string Submap { get; set; }
    }
    [Table("rollinfo")]
    public partial class Rollinfo
    {
        [Column("rollstarttime")]
        public string? Rollstarttime { get; set; }
        [Column("rollendtime")]
        public string? Rollendtime { get; set; }
        [Column("chaosrerolls")]
        public string? Chaosrerolls { get; set; }
        [Column("chaosweight")]
        public string? Chaosweight { get; set; }
        [Column("day")]
        public string? Day { get; set; }
        [Column("season")]
        public string? Season { get; set; }
        [Column("json_agg")]
        public string? JsonAgg { get; set; }
    }
    [Table("statistics")]
    public partial class Statistic
    {
        [Column("turn_id")]
        public string? TurnId { get; set; }
        [Column("season")]
        public string? Season { get; set; }
        [Column("day")]
        public string? Day { get; set; }
        [Column("team")]
        public string? Team { get; set; }
        [Column("rank")]
        public string? Rank { get; set; }
        [Column("territorycount")]
        public string? Territorycount { get; set; }
        [Column("playercount")]
        public string? Playercount { get; set; }
        [Column("merccount")]
        public string? Merccount { get; set; }
        [Column("starpower")]
        public string? Starpower { get; set; }
        [Column("efficiency")]
        public string? Efficiency { get; set; }
        [Column("effectivepower")]
        public string? Effectivepower { get; set; }
        [Column("ones")]
        public string? Ones { get; set; }
        [Column("twos")]
        public string? Twos { get; set; }
        [Column("threes")]
        public string? Threes { get; set; }
        [Column("fours")]
        public string? Fours { get; set; }
        [Column("fives")]
        public string? Fives { get; set; }
        [Column("tname")]
        public string? Tname { get; set; }
        [Column("logo")]
        public string? Logo { get; set; }
        [Column("regions")]
        public string? Regions { get; set; }
    }
    [Table("stats")]
    public partial class Stat
    {
        [Column("team")]
        public string? Team { get; set; }
        [Column("rank")]
        public string? Rank { get; set; }
        [Column("territorycount")]
        public string? Territorycount { get; set; }
        [Column("playercount")]
        public string? Playercount { get; set; }
        [Column("merccount")]
        public string? Merccount { get; set; }
        [Column("starpower")]
        public string? Starpower { get; set; }
        [Column("efficiency")]
        public string? Efficiency { get; set; }
        [Column("effectivepower")]
        public string? Effectivepower { get; set; }
        [Column("ones")]
        public string? Ones { get; set; }
        [Column("twos")]
        public string? Twos { get; set; }
        [Column("threes")]
        public string? Threes { get; set; }
        [Column("fours")]
        public string? Fours { get; set; }
        [Column("fives")]
        public string? Fives { get; set; }
        [Column("turn_id")]
        public string? TurnId { get; set; }
    }
    [Table("team_player_moves")]
    public partial class TeamPlayerMove
    {
        [Column("id")]
        public string? Id { get; set; }
        [Column("season")]
        public string? Season { get; set; }
        [Column("day")]
        public string? Day { get; set; }
        [Column("team")]
        public string? Team { get; set; }
        [Column("player")]
        public string? Player { get; set; }
        [Column("stars")]
        public string? Stars { get; set; }
        [Column("mvp")]
        public string? Mvp { get; set; }
        [Column("territory")]
        public string? Territory { get; set; }
        [Column("regularteam")]
        public string? Regularteam { get; set; }
        [Column("weight")]
        public string? Weight { get; set; }
        [Column("power")]
        public string? Power { get; set; }
        [Column("multiplier")]
        public string? Multiplier { get; set; }
    }
    [Table("teams")]
    public partial class Team
    {
        [Column("id")]
        public string Id { get; set; }
        [Column("tname")]
        public string? Tname { get; set; }
        [Column("tshortname")]
        public string? Tshortname { get; set; }
        [Column("creation_date")]
        public string? CreationDate { get; set; }
        [Column("color_1")]
        public string? Color1 { get; set; }
        [Column("color_2")]
        public string? Color2 { get; set; }
        [Column("logo")]
        public string? Logo { get; set; }
        [Column("seasons")]
        public int[]? Seasons { get; set; }
        [Column("respawn_count")]
        public string RespawnCount { get; set; }
    }
    [Table("territories")]
    public partial class Territory
    {
        [Column("id")]
        public string Id { get; set; }
        [Column("name")]
        public string? Name { get; set; }
        [Column("region")]
        public string? Region { get; set; }
    }
    [Table("territory_adjacency")]
    public partial class TerritoryAdjacency
    {
        [Column("id")]
        public string? Id { get; set; }
        [Column("territory_id")]
        public string? TerritoryId { get; set; }
        [Column("adjacent_id")]
        public string? AdjacentId { get; set; }
        [Column("note")]
        public string? Note { get; set; }
        [Column("min_turn")]
        public string? MinTurn { get; set; }
        [Column("max_turn")]
        public string? MaxTurn { get; set; }
    }
    [Table("territory_neighbor_history")]
    public partial class TerritoryNeighborHistory
    {
        [Column("turn_id")]
        public string? TurnId { get; set; }
        [Column("id")]
        public string? Id { get; set; }
        [Column("neighbors")]
        public string? Neighbors { get; set; }
    }
    [Table("territory_ownership")]
    public partial class TerritoryOwnership
    {
        [Column("id")]
        public string Id { get; set; }
        [Column("territory_id")]
        public string? TerritoryId { get; set; }
        [Column("owner_id")]
        public string? OwnerId { get; set; }
        [Column("previous_owner_id")]
        public string? PreviousOwnerId { get; set; }
        [Column("random_number")]
        public string? RandomNumber { get; set; }
        [Column("timestamp")]
        public string? Timestamp { get; set; }
        [Column("mvp")]
        public string? Mvp { get; set; }
        [Column("turn_id")]
        public string? TurnId { get; set; }
        [Column("is_respawn")]
        public string IsRespawn { get; set; }
    }
    [Table("territory_ownership_with_neighbors")]
    public partial class TerritoryOwnershipWithNeighbor
    {
        [Column("territory_id")]
        public string? TerritoryId { get; set; }
        [Column("day")]
        public string? Day { get; set; }
        [Column("season")]
        public string? Season { get; set; }
        [Column("name")]
        public string? Name { get; set; }
        [Column("tname")]
        public string? Tname { get; set; }
        [Column("region")]
        public string? Region { get; set; }
        [Column("region_name")]
        public string? RegionName { get; set; }
        [Column("neighbors")]
        public string? Neighbors { get; set; }
    }
    [Table("territory_ownership_without_neighbors")]
    public partial class TerritoryOwnershipWithoutNeighbor
    {
        [Column("territory_id")]
        public string? TerritoryId { get; set; }
        [Column("day")]
        public string? Day { get; set; }
        [Column("season")]
        public string? Season { get; set; }
        [Column("name")]
        public string? Name { get; set; }
        [Column("owner")]
        public string? Owner { get; set; }
        [Column("prev_owner")]
        public string? PrevOwner { get; set; }
        [Column("timestamp")]
        public string? Timestamp { get; set; }
        [Column("random_number")]
        public string? RandomNumber { get; set; }
        [Column("mvp")]
        public string? Mvp { get; set; }
    }
    [Table("territory_stats")]
    public partial class TerritoryStat
    {
        [Column("team")]
        public string? Team { get; set; }
        [Column("ones")]
        public string? Ones { get; set; }
        [Column("twos")]
        public string? Twos { get; set; }
        [Column("threes")]
        public string? Threes { get; set; }
        [Column("fours")]
        public string? Fours { get; set; }
        [Column("fives")]
        public string? Fives { get; set; }
        [Column("teampower")]
        public string? Teampower { get; set; }
        [Column("chance")]
        public string? Chance { get; set; }
        [Column("id")]
        public string Id { get; set; }
        [Column("territory")]
        public string? Territory { get; set; }
        [Column("territory_power")]
        public string? TerritoryPower { get; set; }
        [Column("turn_id")]
        public string? TurnId { get; set; }
    }
    [Table("turninfo")]
    public partial class Turninfo
    {
        [Column("id")]
        public string Id { get; set; }
        [Column("season")]
        public string? Season { get; set; }
        [Column("day")]
        public string? Day { get; set; }
        [Column("complete")]
        public string? Complete { get; set; }
        [Column("active")]
        public string? Active { get; set; }
        [Column("finale")]
        public string? Finale { get; set; }
        [Column("chaosrerolls")]
        public string? Chaosrerolls { get; set; }
        [Column("chaosweight")]
        public string? Chaosweight { get; set; }
        [Column("rollendtime")]
        public string? Rollendtime { get; set; }
        [Column("rollstarttime")]
        public string? Rollstarttime { get; set; }
        [Column("allornothingenabled")]
        public string? Allornothingenabled { get; set; }
        [Column("map")]
        public string? Map { get; set; }
    }
    [Table("turns")]
    public partial class Turn
    {
        [Column("id")]
        public string Id { get; set; }
        [Column("user_id")]
        public string? UserId { get; set; }
        [Column("territory")]
        public string? Territory { get; set; }
        [Column("mvp")]
        public string Mvp { get; set; }
        [Column("power")]
        public string? Power { get; set; }
        [Column("multiplier")]
        public string? Multiplier { get; set; }
        [Column("weight")]
        public string? Weight { get; set; }
        [Column("stars")]
        public string? Stars { get; set; }
        [Column("team")]
        public string? Team { get; set; }
        [Column("alt_score")]
        public string? AltScore { get; set; }
        [Column("merc")]
        public string? Merc { get; set; }
        [Column("turn_id")]
        public string? TurnId { get; set; }
    }
    [Table("users")]
    public partial class User
    {
        [Column("id")]
        public string Id { get; set; }
        [Column("uname")]
        public string Uname { get; set; }
        [Column("platform")]
        public string Platform { get; set; }
        [Column("join_date")]
        public string? JoinDate { get; set; }
        [Column("current_team")]
        public string CurrentTeam { get; set; }
        [Column("auth_key")]
        public string? AuthKey { get; set; }
        [Column("overall")]
        public string? Overall { get; set; }
        [Column("turns")]
        public string? Turns { get; set; }
        [Column("game_turns")]
        public string? GameTurns { get; set; }
        [Column("mvps")]
        public string? Mvps { get; set; }
        [Column("streak")]
        public string? Streak { get; set; }
        [Column("awards")]
        public string? Awards { get; set; }
        [Column("role_id")]
        public string? RoleId { get; set; }
        [Column("playing_for")]
        public string? PlayingFor { get; set; }
        [Column("past_teams")]
        public int[]? PastTeams { get; set; }
        [Column("awards_bak")]
        public string? AwardsBak { get; set; }
        [Column("discord_id")]
        public string? DiscordId { get; set; }
        [Column("is_alt")]
        public string? IsAlt { get; set; }
        [Column("must_captcha")]
        public string? MustCaptcha { get; set; }
    }
}

